### PR TITLE
ANJALI KUMARI DUBEY : Week - 2,3&4 PROJECTS

### PR DESCRIPTION
**Pull request by AKD-01**
Submission of Week-2 Projects for frontend development track.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Well done. You are the only person who made the right pr and heard my instructions carefully. Just add the readme which I suggested on tmp-fe-2022 channel on slack

**Comment by AKD-01** [comment]
> Well done. You are the only person who made the right pr and heard my instructions carefully. Just add the readme which I suggested on tmp-fe-2022 channel on slack

Thank you so much, @siddhi-244 !✨ I have added readme.md in all the projects, so please review it again.

**Review by siddhi-244 — APPROVED** [review]
Amazing work

**Comment by AKD-01** [comment]
Thank you!!

**Comment by AKD-01** [comment]
I have submitted the week-3 projects in this pr only as it was approved but wasn't merged. @siddhi-24 could you please check my week-3 projects and merge this pr containing my week-2 & 3 projects, if everything is fine.

**Comment by AKD-01** [comment]
> I have submitted the week-3 projects in this pr only as it was approved but wasn't merged. @Siddhi-24 could you please check my week-3 projects and merge this pr containing my week-2 & 3 projects, if everything is fine.

Now, I have submitted my week-4 projects also in this pr as my projects for week-2 were approved but wasn't merged. @siddhi-244 please check my week-3 and 4 projects and merge this pr if everything is fine asap. Thanks!

**Comment by siddhi-244** [comment]
> > I have submitted the week-3 projects in this pr only as it was approved but wasn't merged. @Siddhi-24 could you please check my week-3 projects and merge this pr containing my week-2 & 3 projects, if everything is fine.
> 
> Now, I have submitted my week-4 projects also in this pr as my projects for week-2 were approved but wasn't merged. @siddhi-244 please check my week-3 and 4 projects and merge this pr if everything is fine asap. Thanks!

I could have merged but I don't have permissions

**Comment by AKD-01** [comment]
> > > I have submitted the week-3 projects in this pr only as it was approved but wasn't merged. @Siddhi-24 could you please check my week-3 projects and merge this pr containing my week-2 & 3 projects, if everything is fine.
> > 
> > 
> > Now, I have submitted my week-4 projects also in this pr as my projects for week-2 were approved but wasn't merged. @siddhi-244 please check my week-3 and 4 projects and merge this pr if everything is fine asap. Thanks!
> 
> I could have merged but I don't have permissions

So, could you please check my week-3 & week-4 projects and if it is fine leave a comment asking the concerned person to merge it. Thanks!

**Review by Duffigoogle — APPROVED** [review]
Nice work...

**Review by Duffigoogle — APPROVED** [review]

**Pull request merged**
