### PR TITLE
Ritik Kumar : Week - 2,3 and 4 PROJECTS

### PR DESCRIPTION
**Pull request by srivastavaritik**
This Pull Request is regarding the Projects that I have made in Week 2 of Techrity Mentorship Program Cohort, 2022, Frontend Track.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
make sure you add readme as I suggested on slack. Rest all is awesome

**Comment by srivastavaritik** [comment]
> make sure you add readme as I suggested on slack. Rest all is awesome

Thanks @siddhi-244 . I have added the readme.md for every project, please check.

**Review by Duffigoogle — APPROVED** [review]
Requested changes are to be effected...

**Review by siddhi-244 — APPROVED** [review]

**Comment by srivastavaritik** [comment]
I have updated this Pull Request and updated my week-3 projects in this pr only. @siddhi-244 please have a look

**Comment by srivastavaritik** [comment]
I have updated this Pull Request and updated my week-4 projects in this pr only. @siddhi-244 please have a look

**Comment by srivastavaritik** [comment]
Hey @siddhi-244 , I have completed my projects till week-4 and my pr have 2 approvals on GitHub but it isn't merged yet. So could you please merge it. Thank you.

**Pull request merged**
