### PR TITLE
Yash Projects 

### PR DESCRIPTION
**Pull request by YashBawa**
Week 5 projects have been added along with week 2,3,4 projects .

### CODE REVIEW

**Comment by siddhi-244** [comment]
> Week 5 projects have been added along with week 2,3,4 projects .

Cool !

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Readme ?

**Comment by YashBawa** [comment]
Ya sorry , currently am updating the files and will notify as soon as it has to be reviewed!!

**Comment by YashBawa** [comment]
@siddhi-244 now its complete with all content please review and verify it.
Thanks

**Comment by YashBawa** [comment]
@siddhi-244 Week-5 and Week-6 projects have been added along with all the details including the readme files.
Please review and verify it.
Thank you

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
