### PR TITLE
final project submission

### PR DESCRIPTION
**Pull request by faozziyyah**

### CODE REVIEW

**Comment by Duffigoogle** [comment]
*Live Site URL link not working as expected.
*Layout & Responsiveness on point.
Awesome job!

**Review by Duffigoogle — APPROVED** [review]
*Live Site URL link not working as expected.
*Layout & Responsiveness on point.
Awesome job!

**Comment by owans** [comment]
@faozziyyah @teekaytech Please see that this change is implemented before the  #tmp2021 demo day and we will merge your PR. Thank you!

**Comment by faozziyyah** [comment]
I've made changes to all the files, remove comments and all forms of console.log. I've also updated the live link in the readme file.

**Pull request merged**
