### PR TITLE
Yash Bawa - Week 2,3 and 4 projects 

### PR DESCRIPTION
**Pull request by YashBawa**
All projects are completed along with Readme and combined in a single folder.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Try to add screenshots of projects in readme.

**Comment by YashBawa** [comment]
Added Screenshots and updated the readme file .

**Comment by YashBawa** [comment]
Hey @siddhi-244 , can you please review all the projects of week 2 and 3 and verify it .

**Comment by YashBawa** [comment]
@siddhi-244 please review week 4 projects and verify it.
Thank you

**Review by siddhi-244 — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please check the merged project readme ! Change your readme accordingly

**Comment by YashBawa** [comment]
Hey, @siddhi-244 I have updated the readme to all projects please review and merge them. 
Thanks

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
